* Encoding: UTF-8.
USE ALL.
COMPUTE filter_$=(Exclude = 0).
VARIABLE LABELS filter_$ 'Exclude = 0 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.

CORRELATIONS
  /MISSING=PAIRWISE.
  
 BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZVolunteeringChoice ZDonatedLastYear ZIndividualizing ZBinding
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
CORRELATIONS
  /VARIABLES=ZVolunteeringChoice ZDonatedLastYear ZIndividualizing ZBinding
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZVolunteeringChoice ZAmountMax5000 ZHelpedBeggars ZIndividualizing ZBinding
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
NONPAR CORR
  /VARIABLES=ZVolunteeringChoice ZAmountMax5000 ZHelpedBeggars ZIndividualizing ZBinding
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



USE ALL.
COMPUTE filter_$=(Exclude = 0 and VolunteeringChoice = 2).
VARIABLE LABELS filter_$ 'Exclude = 0 and VolunteeringChoice = 2 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZInAll ZIngroupDilemma ZConcIn ZConcOut ZIndividualizing ZBinding
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
CORRELATIONS
  /VARIABLES=ZInAll ZIngroupDilemma ZConcIn ZConcOut ZIndividualizing ZBinding
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZOutAll ZIngroupDilemma ZConcIn ZConcOut ZIndividualizing ZBinding
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
CORRELATIONS
  /VARIABLES=ZOutAll ZIngroupDilemma ZConcIn ZConcOut ZIndividualizing ZBinding
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZInAll ZOutAll ZHelpedBeggars
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
NONPAR CORR
  /VARIABLES=ZInAll ZOutAll ZHelpedBeggars
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


USE ALL.
COMPUTE filter_$=(Exclude = 0).
VARIABLE LABELS filter_$ 'Exclude = 0 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.


BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZIndividualizing ZBinding ZRes ZPref ZJustW ZSpir
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
CORRELATIONS
  /VARIABLES=ZIndividualizing ZBinding ZRes ZPref ZJustW ZSpir
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZIndividualizing ZBinding ZLR ZAge ZGender
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
CORRELATIONS
  /VARIABLES=ZIndividualizing ZBinding ZLR ZAge ZGender
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

BOOTSTRAP
  /SAMPLING METHOD=SIMPLE
  /VARIABLES INPUT=ZIndividualizing ZBinding ZRel ZEdu
  /CRITERIA CILEVEL=95 CITYPE=BCA  NSAMPLES=10000
  /MISSING USERMISSING=EXCLUDE.
NONPAR CORR
  /VARIABLES=ZIndividualizing ZBinding ZRel ZEdu
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


USE ALL.
COMPUTE filter_$=(Exclude = 0 and VolunteeringChoice = 2).
VARIABLE LABELS filter_$ 'Exclude = 0 and VolunteeringChoice = 2 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.



LOGISTIC REGRESSION VARIABLES IngroupAllocation 
  /METHOD=ENTER ZIndividualizing ZBinding ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

LOGISTIC REGRESSION VARIABLES IngroupAllocation 
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).


LOGISTIC REGRESSION VARIABLES OutgroupAllocation 
  /METHOD=ENTER ZIndividualizing ZBinding ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

LOGISTIC REGRESSION VARIABLES OutgroupAllocation 
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).


USE ALL.
COMPUTE filter_$=(Exclude = 0).
VARIABLE LABELS filter_$ 'Exclude = 0 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.


LOGISTIC REGRESSION VARIABLES VolunteeringChoice 
  /METHOD=ENTER ZIndividualizing ZBinding ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

LOGISTIC REGRESSION VARIABLES VolunteeringChoice 
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).


LOGISTIC REGRESSION VARIABLES DonatedLastYear 
  /METHOD=ENTER ZIndividualizing ZBinding ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

LOGISTIC REGRESSION VARIABLES DonatedLastYear 
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity ZRel ZSpir ZRes ZPref ZJustW ZLR ZAge ZGender ZEdu 
  /CONTRAST (ZGender)=Indicator 
  /PRINT=CI(95) 
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZIngroupDilemma
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZIndividualizing ZBinding.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZIngroupDilemma
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity.



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZHelpedBeggars
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZIndividualizing ZBinding.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZHelpedBeggars
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity.



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZAmountMax5000
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZIndividualizing ZBinding.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZAmountMax5000
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity.



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZConcIn
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZIndividualizing ZBinding.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZConcIn
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity.


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZConcOut
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZIndividualizing ZBinding.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT ZConcOut
  /METHOD=ENTER ZAge ZGender ZEdu ZJustW ZRes ZPref ZLR ZSpir ZRel
  /METHOD=ENTER ZHarm ZFairness ZLoyalty ZAuthority ZSanctity.

