#include "tree_sitter/alloc.h"
#include "tree_sitter/array.h"
#include "tree_sitter/parser.h"
#include <ctype.h>
#include <stdbool.h>
#include <string.h>

enum TokenType { ID };

const char *commands[] = {
    "2SLS",
    "ACF",
    "ADD DOCUMENT",
    "ADD FILES",
    "ADD VALUE LABELS",
    "ADP",
    "AGGREGATE",
    "AIM",
    "ALSCAL",
    "ALTER TYPE",
    "ANACOR",
    "ANOVA",
    "APPLY DICTIONARY",
    "AREG",
    "ARIMA",
    "AUTORECODE",
    "BAYES ANOVA",
    "BAYES CORRELATION",
    "BAYES INDEPENDENT",
    "BAYES LOGLINEAR",
    "BAYES ONESAMPLE",
    "BAYES ONESAMPLE",
    "BAYES ONESAMPLE",
    "BAYES REGRESSION",
    "BAYES RELATED",
    "BAYES REPEATED",
    "BEGIN DATA",
    "BEGIN EXPR",
    "BEGIN EXPR-END EXPR",
    "BEGIN GPL-END GPL",
    "BOOTSTRAP",
    "BREAK",
    "CACHE",
    "CASEPLOT",
    "CASESTOVARS",
    "CATREG",
    "CD",
    "CLABELS",
    "CLEAR TIME PROGRAM",
    "CLEAR TRANSFORMATIONS",
    "CLUSTER",
    "CNLR",
    "CODEBOOK",
    "COMMENT",
    "COMPARE DATASETS",
    "COMPUTE",
    "CONJOINT",
    "CONSTRAINED FUNCTIONS",
    "CORRELATIONS",
    "CORRESPONDENCE",
    "COUNT",
    "COXREG",
    "CREATE",
    "CROSSTABS",
    "CSCOXREG",
    "CSDESCRIPTIVES",
    "CSGLM",
    "CSLOGISTIC",
    "CSORDINAL",
    "CSPLAN",
    "CSSELECT",
    "CSTABULATE",
    "CTABLES",
    "CURVEFIT",
    "DATA LIST",
    "DATAFILE ATTRIBUTE",
    "DATASET ACTIVATE",
    "DATASET CLOSE",
    "DATASET COPY",
    "DATASET DECLARE",
    "DATASET DISPLAY",
    "DATASET NAME",
    "DATE",
    "DEFINE",
    "DELETE VARIABLES",
    "DERIVATIVES",
    "DESCRIPTIVES",
    "DETECTANOMALY",
    "DISCRIMINANT",
    "DISPLAY",
    "DO IF",
    "DO REPEAT",
    "DOCUMENT",
    "DROP DOCUMENTS",
    "ECHO",
    "END CASE",
    "END FILE",
    "ERASE",
    "EXAMINE",
    "EXECUTE",
    "EXPORT",
    "EXSMOOTH",
    "EXTENSION",
    "FACTOR",
    "FILE HANDLE",
    "FILE LABEL",
    "FILE TYPE",
    "FILTER",
    "FINISH",
    "FIT",
    "FLEISS MULTIRATER KAPPA",
    "FLIP",
    "FORMATS",
    "FREQUENCIES",
    "GENLIN",
    "GENLINMIXED",
    "GENLOG",
    "GET",
    "GET CAPTURE",
    "GET DATA",
    "GET SAS",
    "GET STATA",
    "GET TRANSLATE",
    "GETCOGNOS",
    "GETTM1",
    "GGRAPH",
    "GLM",
    "GRAPH",
    "HILOGLINEAR",
    "HOMALS",
    "HOST",
    "IBREAK",
    "IDO",
    "IDOEND",
    "IGRAPH",
    "IIF",
    "IIFEND",
    "ILET",
    "IMPORT",
    "INCLUDE",
    "INPUT PROGRAM",
    "INSERT",
    "INSERT EXEC",
    "INSERT EXEC",
    "INSERT HIDDDEN",
    "INSERT HIDDEN",
    "KEYED DATA LIST",
    "KM",
    "KNN",
    "LINEAR",
    "LIST",
    "LOGISTIC REGRESSION",
    "LOGLINEAR",
    "LOOP",
    "MANOVA",
    "MATCH FILES",
    "MATRIX",
    "MATRIX DATA",
    "MCONVERT",
    "MEANS",
    "MISSING VALUES",
    "MIXED",
    "MLP",
    "MODEL CLOSE",
    "MODEL HANDLE",
    "MODEL LIST",
    "MODEL NAME",
    "MODEL PROGRAM",
    "MRSETS",
    "MULT RESPONSE",
    "MULTIPLE CORRESPONDENCE",
    "MULTIPLE IMPUTATION",
    "MVA",
    "N OF CASES",
    "NAIVEBAYES",
    "NEW FILE",
    "NLR",
    "NOMREG",
    "NONPAR CORR",
    "NPAR TESTS",
    "NPTESTS",
    "NUMERIC",
    "OLAP CUBES",
    "OMS",
    "OMSEND",
    "OMSINFO",
    "OMSLOG",
    "ONEWAY",
    "OPTIMAL BINNING",
    "ORTHOPLAN",
    "OUTPUT MODIFY",
    "OUTPUT NAME",
    "OUTPUT NEW",
    "OUTPUT OPEN",
    "OUTPUT SAVE",
    "OVERALS",
    "PACF",
    "PARTIAL CORR",
    "PERMISSIONS",
    "PLANCARDS",
    "PLS",
    "PLUM",
    "POINT",
    "POWER MEANS INDEPENDENT",
    "POWER MEANS INDEPENDENT",
    "POWER MEANS ONESAMPLE",
    "POWER MEANS ONESAMPLE",
    "POWER MEANS RELATED",
    "POWER MEANS RELATED",
    "POWER ONEWAY ANOVA",
    "POWER ONEWAY ANOVA",
    "POWER PARTIALCORR",
    "POWER PARTIALCORR",
    "POWER PEARSON ONESAMPLE",
    "POWER PEARSON ONESAMPLE",
    "POWER PROPORTIONS INDEPENDENT",
    "POWER PROPORTIONS INDEPENDENT",
    "POWER PROPORTIONS ONESAMPLE",
    "POWER PROPORTIONS ONESAMPLE",
    "POWER PROPORTIONS RELATED",
    "POWER PROPORTIONS RELATED",
    "POWER SPEARMAN ONESAMPLE",
    "POWER SPEARMAN ONESAMPLE",
    "POWER UNIVARIATE LINEAR",
    "POWER UNIVARIATE LINEAR",
    "PPLOT",
    "PREDICT",
    "PREFSCAL",
    "PRESERVE",
    "PRINCALS",
    "PRINT",
    "PRINT EJECT",
    "PRINT FORMATS",
    "PRINT SPACE",
    "PROBIT",
    "PROCEDURE OUTPUT",
    "PROPORTIONS",
    "PROXIMITIES",
    "PROXSCAL",
    "QUANTILE REGRESSION",
    "QUICK CLUSTER",
    "RANK",
    "RATIO STATISTICS",
    "RBF",
    "READ MODEL",
    "RECODE",
    "RECORD TYPE",
    "REGRESSION",
    "RELIABILITY",
    "RENAME",
    "RENAME VARIABLES",
    "REPEATING DATA",
    "REPORT",
    "REPOSITORY ATTRIBUTES",
    "REPOSITORY CONNECT",
    "REPOSITORY COPY",
    "REREAD",
    "RESPONSE RATE",
    "RESTORE",
    "RMV",
    "ROC",
    "ROC ANALYSIS",
    "ROC ANALYSIS",
    "SAMPLE",
    "SAVE",
    "SAVE CODEPAGE",
    "SAVE CODEPAGE",
    "SAVE DATA COLLECTION",
    "SAVE MODEL",
    "SAVE TRANSLATE",
    "SCRIPT",
    "SEASON",
    "SELECT IF",
    "SELECTPRED",
    "SET",
    "SHIFT VALUES",
    "SHOW",
    "SIMPLAN",
    "SIMPREP BEGIN",
    "SIMRUN",
    "SORT",
    "SORT CASES",
    "SORT VARIABLES",
    "SPATIAL ASSOCIATION RULES",
    "SPATIAL ASSOCIATION RULES",
    "SPATIAL MAPSPEC",
    "SPATIAL MAPSPEC",
    "SPATIAL TEMPORAL PREDICTION",
    "SPATIAL TEMPORAL PREDICTION",
    "SPCHART",
    "SPECTRA",
    "SPLIT FILE",
    "STAR JOIN",
    "STRING",
    "SUBTITLE",
    "SUMMARIZE",
    "SURVIVAL",
    "SYSFILE INFO",
    "T-TEST",
    "TCM ANALYSIS",
    "TCM APPLY",
    "TCM MODEL",
    "TDISPLAY",
    "TEMPORARY",
    "TIME PROGRAM",
    "TITLE",
    "TMS BEGIN",
    "TMS END",
    "TMS IMPORT",
    "TMS MERGE",
    "TREE",
    "TSAPPLY",
    "TSET",
    "TSHOW",
    "TSMODEL",
    "TSPLOT",
    "TWOSTEP CLUSTER",
    "UNIANOVA",
    "UPDATE",
    "USE",
    "VALIDATEDATA",
    "VALUE LABELS",
    "VARCOMP",
    "VARIABLE ALIGNMENT",
    "VARIABLE ATTRIBUTE",
    "VARIABLE LABELS",
    "VARIABLE LEVEL",
    "VARIABLE ROLE",
    "VARIABLE WIDTH",
    "VARSTOCASES",
    "VECTOR",
    "VERIFY",
    "WEIGHT",
    "WEIGHTED KAPPA",
    "WLS",
    "WRITE",
    "WRITE FORMATS",
    "XGRAPH",
    "XSAVE",
};

const size_t command_count = sizeof(commands) / sizeof(commands[0]);

// NOTE: The most important one

// Scan
bool tree_sitter_spss_external_scanner_scan(void *payload, TSLexer *lexer,
                                            const bool *valid_symbols) {
  // Skip any leading whitespace
  while (isspace(lexer->lookahead)) {
    lexer->advance(lexer, true);
  }

  // Buffer to store the potential keyword
  char buffer[32];
  size_t length = 0;

  // Read characters into the buffer
  while (isalnum(lexer->lookahead) || lexer->lookahead == ' ') {
    if (length < sizeof(buffer) - 1) {
      buffer[length++] = toupper(lexer->lookahead);
    }
    lexer->advance(lexer, false);
  }
  buffer[length] = '\0';

  // Check if the buffer matches any keyword
  for (size_t i = 0; i < command_count; i++) {
    if (strcmp(buffer, commands[i]) == 0) {
      // Set the appropriate token
      lexer->result_symbol = ID;
      return true;
    }
  }

  return false;
}

// NOTE: The below 4 are less important

// Create
void *tree_sitter_spss_external_scanner_create() {
  // ...
}

// Destroy
void tree_sitter_spss_external_scanner_destroy(void *payload) {
  // ...
}

// Serialize
unsigned tree_sitter_spss_external_scanner_serialize(void *payload,
                                                     char *buffer) {
  // ...
}

// Deserialize
void tree_sitter_spss_external_scanner_deserialize(void *payload,
                                                   const char *buffer,
                                                   unsigned length) {
  // ...
}
